defaults: &defaults
  :verbose: true
  :pidfile: ./tmp/sidekiq.pid
  :queues:
    - default
  :concurrency: 1

development:
  <<: *defaults

production:
  <<: *defaults
  :logfile: ./log/sidekiq.log
  :concurrency: 25
