defaults: &defaults
  :verbose: true
  :pidfile: ./tmp/sidekiq.pid
  :queues:
    - [critical, 4]
    - [high_priority, 3]
    - [default, 2]
    - [low_priority, 1]
  :concurrency: 1

development:
  <<: *defaults

production:
  <<: *defaults
  :logfile: ./log/sidekiq.log
  :concurrency: 25
